# Mistral-7B-Instruct Configuration
name: /share/home/tm902089733300000/a903202310/lys/models/Mistral-7B-Instruct-v0.3

attn_implementation: eager
dtype: bfloat16
load_in_4bit: false
load_in_8bit: false
device_map: auto

n_layers: 32
n_heads: 32
hidden_size: 4096
trust_remote_code: false
