name: ensemble
cls_path: src.methods.ensemble.EnsembleMethod

classifier: logistic
cv_folds: 5
random_seed: ${seed}

params:
  base_methods:
    - lapeigvals
    - entropy
  ensemble_type: stacking  # voting, stacking, concat