name: entropy
cls_path: src.methods. entropy.EntropyMethod

classifier: logistic
cv_folds: 5
random_seed: ${seed}

params: 
  use_token_entropy: true
  use_attention_entropy: true
  aggregation:  mean