name: lapeigvals
cls_path:  src.methods.lapeigvals.LapEigvalsMethod

classifier:  logistic
cv_folds: 5
random_seed: ${seed}

# Method specific parameters
params:
  top_k_eigenvalues: 10
  use_diagonal_only: true
  aggregate_layers: all  # all, last, mean
  aggregate_heads: all   # all, mean